<?php

namespace Database\Seeders;

use App\Models\Attraction;
use App\Models\Civilization;
use App\Models\Region;
use Illuminate\Database\Seeder;

class AttractionSeeder extends Seeder
{
    public function run(): void
    {
        $ancient = Civilization::query()->where('name', 'Ancient Egypt')->firstOrFail();
        $islamic = Civilization::query()->where('name', 'Islamic')->firstOrFail();
        $coptic = Civilization::query()->where('name', 'Coptic')->firstOrFail();
        $grecoRoman = Civilization::query()->where('name', 'Greco-Roman')->firstOrFail();

        $cairo = Region::query()->where('name', 'Cairo')->firstOrFail();
        $luxor = Region::query()->where('name', 'Luxor')->firstOrFail();
        $aswan = Region::query()->where('name', 'Aswan')->firstOrFail();
        $alexandria = Region::query()->where('name', 'Alexandria')->firstOrFail();
        $redSea = Region::query()->where('name', 'Red Sea')->firstOrFail();
        $southSinai = Region::query()->where('name', 'South Sinai')->firstOrFail();
        $matrouh = Region::query()->where('name', 'Matrouh')->firstOrFail();
        $modern = Civilization::query()->where('name', 'Modern Civilization')->firstOrFail();

        $items = [
            [
                'seed_key' => 'pyramids-of-giza',
                'name' => 'Pyramids of Giza',
                'description' => 'The iconic complex including the Great Pyramid and Sphinx.',
                'image' => 'images/attractions/the-pyramids-of-giza.jpg',
                'type' => 'historical',
                'location' => 'Giza Plateau, Cairo',
                'city' => 'Cairo',
                'civilization_id' => $ancient->id,
                'region_id' => $cairo->id,
            ],
            [
                'seed_key' => 'karnak-temple',
                'name' => 'Karnak Temple',
                'description' => 'A vast temple complex built over many generations of pharaohs.',
                'image' => 'images/attractions/karnak-temple.jpg',
                'type' => 'historical',
                'location' => 'Luxor',
                'city' => 'Luxor',
                'civilization_id' => $ancient->id,
                'region_id' => $luxor->id,
            ],
            [
                'seed_key' => 'abu-simbel-temples',
                'name' => 'Abu Simbel Temples',
                'description' => 'Rock temples commissioned by Ramesses II near Lake Nasser.',
                'image' => 'images/attractions/abu-simbel-temples.jpg',
                'type' => 'historical',
                'location' => 'Aswan',
                'city' => 'Aswan',
                'civilization_id' => $ancient->id,
                'region_id' => $aswan->id,
            ],
            [
                'seed_key' => 'citadel-of-cairo',
                'name' => 'Citadel of Cairo',
                'description' => 'Historic Islamic fortress with panoramic city views.',
                'image' => 'images/attractions/citadel-of-cairo.jpg',
                'type' => 'historical',
                'location' => 'Cairo',
                'city' => 'Cairo',
                'civilization_id' => $islamic->id,
                'region_id' => $cairo->id,
            ],
            [
                'seed_key' => 'hanging-church',
                'name' => 'Hanging Church',
                'description' => 'One of the oldest Coptic churches in Old Cairo.',
                'image' => 'images/attractions/hanging-church.jpg',
                'type' => 'historical',
                'location' => 'Old Cairo',
                'city' => 'Cairo',
                'civilization_id' => $coptic->id,
                'region_id' => $cairo->id,
            ],
            [
                'seed_key' => 'catacombs-of-kom-el-shoqafa',
                'name' => 'Catacombs of Kom El Shoqafa',
                'description' => 'A major Greco-Roman burial site in Alexandria.',
                'image' => 'images/attractions/catacombs-of-kom-el-shoqafa.jpg',
                'type' => 'historical',
                'location' => 'Alexandria',
                'city' => 'Alexandria',
                'civilization_id' => $grecoRoman->id,
                'region_id' => $alexandria->id,
            ],
            [
                'seed_key' => 'hurghada-beaches',
                'name' => 'Hurghada Beaches',
                'description' => 'Crystal-clear Red Sea waters, vibrant reefs, and lively beachfront resorts.',
                'image' => 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?auto=format&fit=crop&w=1400&q=80',
                'type' => 'beach',
                'location' => 'Hurghada',
                'city' => 'Hurghada',
                'civilization_id' => $modern->id,
                'region_id' => $redSea->id,
            ],
            [
                'seed_key' => 'sharm-el-sheikh',
                'name' => 'Sharm El Sheikh',
                'description' => 'World-class diving spots, coral-rich bays, and sunny coastal promenades.',
                'image' => 'https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=1400&q=80',
                'type' => 'beach',
                'location' => 'Sharm El Sheikh',
                'city' => 'Sharm El Sheikh',
                'civilization_id' => $modern->id,
                'region_id' => $southSinai->id,
            ],
            [
                'seed_key' => 'dahab-blue-lagoon',
                'name' => 'Dahab Blue Lagoon',
                'description' => 'Relaxed beach atmosphere, turquoise waters, and adventure-friendly shoreline.',
                'image' => 'https://images.unsplash.com/photo-1493558103817-58b2924bce98?auto=format&fit=crop&w=1400&q=80',
                'type' => 'beach',
                'location' => 'Dahab',
                'city' => 'Dahab',
                'civilization_id' => $modern->id,
                'region_id' => $southSinai->id,
            ],
            [
                'seed_key' => 'alexandria-corniche',
                'name' => 'Alexandria Corniche',
                'description' => 'Historic Mediterranean waterfront with sea views, cafes, and city landmarks.',
                'image' => 'https://images.unsplash.com/photo-1473116763249-2faaef81ccda?auto=format&fit=crop&w=1400&q=80',
                'type' => 'coastal',
                'location' => 'Alexandria',
                'city' => 'Alexandria',
                'civilization_id' => $modern->id,
                'region_id' => $alexandria->id,
            ],
            [
                'seed_key' => 'el-gouna-marina',
                'name' => 'El Gouna Marina',
                'description' => 'A modern coastal lifestyle destination with marinas, lagoons, and beach clubs.',
                'image' => 'https://images.unsplash.com/photo-1454391304352-2bf4678b1a7a?auto=format&fit=crop&w=1400&q=80',
                'type' => 'coastal',
                'location' => 'El Gouna',
                'city' => 'El Gouna',
                'civilization_id' => $modern->id,
                'region_id' => $redSea->id,
            ],
            [
                'seed_key' => 'north-coast-beaches',
                'name' => 'North Coast Beaches',
                'description' => 'Long white-sand shoreline and resort towns ideal for summer escapes.',
                'image' => 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1400&q=80',
                'type' => 'coastal',
                'location' => 'Marsa Matrouh',
                'city' => 'Marsa Matrouh',
                'civilization_id' => $modern->id,
                'region_id' => $matrouh->id,
            ],
            [
                'seed_key' => 'nile-felucca-ride-cairo',
                'name' => 'Nile Felucca Ride',
                'description' => 'A traditional sailboat experience on the Nile at sunset in Cairo, offering calm water, city views, and a relaxed way to enjoy the river before evening lights come on.',
                'image' => 'https://images.unsplash.com/photo-1544198365-f5d60b6d8190?auto=format&fit=crop&w=1400&q=80',
                'type' => 'activity',
                'location' => 'Nile Corniche, Cairo',
                'city' => 'Cairo',
                'civilization_id' => $modern->id,
                'region_id' => $cairo->id,
            ],
            [
                'seed_key' => 'khan-el-khalili-walking-tour',
                'name' => 'Khan El Khalili Walking Tour',
                'description' => 'Guided evening walk through the historic bazaar streets and alleys, with time to explore hidden lanes, traditional shops, and the lively atmosphere of old Cairo.',
                'image' => 'https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&w=1400&q=80',
                'type' => 'activity',
                'location' => 'Khan El Khalili, Cairo',
                'city' => 'Cairo',
                'civilization_id' => $modern->id,
                'region_id' => $cairo->id,
            ],
            [
                'seed_key' => 'egyptian-museum-guided-tour',
                'name' => 'Egyptian Museum Guided Tour',
                'description' => 'Expert-led museum tour covering iconic royal and archaeological collections, giving visitors context, highlights, and the stories behind Egypt\'s most famous artifacts.',
                'image' => 'https://images.unsplash.com/photo-1595665593673-bf1ad72905c0?auto=format&fit=crop&w=1400&q=80',
                'type' => 'activity',
                'location' => 'Tahrir Square, Cairo',
                'city' => 'Cairo',
                'civilization_id' => $modern->id,
                'region_id' => $cairo->id,
            ],
            [
                'seed_key' => 'camel-ride-giza-plateau',
                'name' => 'Camel Ride at Giza Plateau',
                'description' => 'A desert-edge camel ride with panoramic views of the pyramids, combining a classic desert experience with one of the most recognizable landscapes in the world.',
                'image' => 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?auto=format&fit=crop&w=1400&q=80',
                'type' => 'activity',
                'location' => 'Giza Plateau',
                'city' => 'Cairo',
                'civilization_id' => $modern->id,
                'region_id' => $cairo->id,
            ],
            [
                'seed_key' => 'hot-air-balloon-luxor',
                'name' => 'Hot Air Balloon Luxor',
                'description' => 'Sunrise balloon flight over the West Bank temples and fields, with wide aerial views of the Nile Valley and a quiet, memorable start to the day.',
                'image' => 'https://images.unsplash.com/photo-1518895949257-7621c3c786d7?auto=format&fit=crop&w=1400&q=80',
                'type' => 'activity',
                'location' => 'West Bank, Luxor',
                'city' => 'Luxor',
                'civilization_id' => $modern->id,
                'region_id' => $luxor->id,
            ],
            [
                'seed_key' => 'luxor-west-bank-guided-tour',
                'name' => 'Luxor West Bank Guided Tour',
                'description' => 'A curated day trip across royal tombs and ancient temple complexes, designed to connect the monuments, history, and landscape of Luxor\'s West Bank in one route.',
                'image' => 'https://images.unsplash.com/photo-1568322445389-f64ac2515020?auto=format&fit=crop&w=1400&q=80',
                'type' => 'activity',
                'location' => 'West Bank, Luxor',
                'city' => 'Luxor',
                'civilization_id' => $modern->id,
                'region_id' => $luxor->id,
            ],
            [
                'seed_key' => 'karnak-sound-and-light-show',
                'name' => 'Karnak Sound and Light Show',
                'description' => 'Nighttime storytelling experience across illuminated temple halls, where lights, narration, and music bring the ancient temple setting to life after dark.',
                'image' => 'https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?auto=format&fit=crop&w=1400&q=80',
                'type' => 'activity',
                'location' => 'Karnak Temple, Luxor',
                'city' => 'Luxor',
                'civilization_id' => $modern->id,
                'region_id' => $luxor->id,
            ],
            [
                'seed_key' => 'nubian-village-visit-aswan',
                'name' => 'Nubian Village Visit',
                'description' => 'Cultural village visit with local crafts, cuisine, and Nubian traditions, offering a warm look at daily life, hospitality, and heritage along the Nile in Aswan.',
                'image' => 'https://images.unsplash.com/photo-1559508551-44bff1de756b?auto=format&fit=crop&w=1400&q=80',
                'type' => 'activity',
                'location' => 'Nubian Village, Aswan',
                'city' => 'Aswan',
                'civilization_id' => $modern->id,
                'region_id' => $aswan->id,
            ],
            [
                'seed_key' => 'aswan-felucca-sunset-sail',
                'name' => 'Aswan Felucca Sunset Sail',
                'description' => 'Relaxing Nile sail around islands with sunset views over Aswan, ideal for a peaceful evening on the water with soft light and scenic riverbank views.',
                'image' => 'https://images.unsplash.com/photo-1473496169904-658ba7c44d8a?auto=format&fit=crop&w=1400&q=80',
                'type' => 'activity',
                'location' => 'Aswan Nile Corniche',
                'city' => 'Aswan',
                'civilization_id' => $modern->id,
                'region_id' => $aswan->id,
            ],
            [
                'seed_key' => 'philae-night-show',
                'name' => 'Philae Night Show',
                'description' => 'An immersive evening show at Philae with music and light effects, turning the temple visit into a dramatic experience that highlights the monument\'s atmosphere and history.',
                'image' => 'https://images.unsplash.com/photo-1666170904295-4ce7fd64a4b6?auto=format&fit=crop&w=1400&q=80',
                'type' => 'activity',
                'location' => 'Philae Temple, Aswan',
                'city' => 'Aswan',
                'civilization_id' => $modern->id,
                'region_id' => $aswan->id,
            ],
            [
                'seed_key' => 'alexandria-seafood-food-tour',
                'name' => 'Alexandria Seafood Food Tour',
                'description' => 'Guided tasting tour across famous seafood spots on the Mediterranean coast, mixing local flavors, waterfront walks, and stops at some of Alexandria\'s best-known restaurants.',
                'image' => 'https://images.unsplash.com/photo-1559847844-5315695dadae?auto=format&fit=crop&w=1400&q=80',
                'type' => 'activity',
                'location' => 'Alexandria Waterfront',
                'city' => 'Alexandria',
                'civilization_id' => $modern->id,
                'region_id' => $alexandria->id,
            ],
            [
                'seed_key' => 'qaitbay-citadel-tour',
                'name' => 'Qaitbay Citadel Tour',
                'description' => 'Coastal fortress walk with historical context and sea panoramas, offering a mix of architecture, maritime history, and open Mediterranean views from the fortress edge.',
                'image' => 'https://images.unsplash.com/photo-1516483638261-f4dbaf036963?auto=format&fit=crop&w=1400&q=80',
                'type' => 'activity',
                'location' => 'Qaitbay Citadel, Alexandria',
                'city' => 'Alexandria',
                'civilization_id' => $modern->id,
                'region_id' => $alexandria->id,
            ],
            [
                'seed_key' => 'alexandria-corniche-cycling',
                'name' => 'Alexandria Corniche Cycling',
                'description' => 'Leisure cycling route along the Corniche with seaside city views, making it easy to enjoy the sea breeze, urban scenery, and a flexible stop-and-go sightseeing pace.',
                'image' => 'https://images.unsplash.com/photo-1476611338391-6f395a0ebc7b?auto=format&fit=crop&w=1400&q=80',
                'type' => 'activity',
                'location' => 'Corniche Road, Alexandria',
                'city' => 'Alexandria',
                'civilization_id' => $modern->id,
                'region_id' => $alexandria->id,
            ],
            [
                'seed_key' => 'hurghada-snorkeling-trip',
                'name' => 'Hurghada Snorkeling Trip',
                'description' => 'Boat-based snorkeling experience across vibrant Red Sea coral reefs, with clear water, colorful marine life, and several chances to swim in protected offshore spots.',
                'image' => 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=1400&q=80',
                'type' => 'activity',
                'location' => 'Hurghada Marina',
                'city' => 'Hurghada',
                'civilization_id' => $modern->id,
                'region_id' => $redSea->id,
            ],
            [
                'seed_key' => 'hurghada-scuba-diving',
                'name' => 'Hurghada Scuba Diving',
                'description' => 'Guided diving sessions for reef exploration and marine life encounters, suitable for visitors who want a deeper underwater experience with professional supervision and equipment support.',
                'image' => 'https://images.unsplash.com/photo-1682687982501-1e58ab814714?auto=format&fit=crop&w=1400&q=80',
                'type' => 'activity',
                'location' => 'Hurghada Dive Sites',
                'city' => 'Hurghada',
                'civilization_id' => $modern->id,
                'region_id' => $redSea->id,
            ],
            [
                'seed_key' => 'el-gouna-kitesurfing',
                'name' => 'El Gouna Kitesurfing',
                'description' => 'Wind-friendly lagoon sessions for beginner and advanced kitesurfers, with open water, steady breezes, and the kind of setting that works well for lessons or longer rides.',
                'image' => 'https://images.unsplash.com/photo-1502680390469-be75c86b636f?auto=format&fit=crop&w=1400&q=80',
                'type' => 'activity',
                'location' => 'El Gouna Lagoon',
                'city' => 'El Gouna',
                'civilization_id' => $modern->id,
                'region_id' => $redSea->id,
            ],
            [
                'seed_key' => 'ras-mohamed-boat-trip',
                'name' => 'Ras Mohamed Boat Trip',
                'description' => 'Full-day marine reserve excursion with snorkeling stops and clear waters, giving visitors access to one of Sinai\'s most scenic coastal environments and reef-rich waters.',
                'image' => 'https://images.unsplash.com/photo-1520763185298-1b434c919102?auto=format&fit=crop&w=1400&q=80',
                'type' => 'activity',
                'location' => 'Ras Mohamed, Sharm El Sheikh',
                'city' => 'Sharm El Sheikh',
                'civilization_id' => $modern->id,
                'region_id' => $southSinai->id,
            ],
            [
                'seed_key' => 'dahab-blue-hole-diving',
                'name' => 'Dahab Blue Hole Diving',
                'description' => 'Iconic diving experience at one of Sinai\'s best-known underwater sites, combining adventure, underwater visibility, and a destination that attracts divers from around the world.',
                'image' => 'https://images.unsplash.com/photo-1682687982185-5310a7f6f007?auto=format&fit=crop&w=1400&q=80',
                'type' => 'activity',
                'location' => 'Blue Hole, Dahab',
                'city' => 'Dahab',
                'civilization_id' => $modern->id,
                'region_id' => $southSinai->id,
            ],
            [
                'seed_key' => 'marsa-matrouh-beach-camping',
                'name' => 'Marsa Matrouh Beach Camping',
                'description' => 'Overnight coastal camping with beach activities and stargazing, ideal for travelers who want a slower, more open-air experience on the Mediterranean shore.',
                'image' => 'https://images.unsplash.com/photo-1493558103817-58b2924bce98?auto=format&fit=crop&w=1400&q=80',
                'type' => 'activity',
                'location' => 'Marsa Matrouh Coast',
                'city' => 'Marsa Matrouh',
                'civilization_id' => $modern->id,
                'region_id' => $matrouh->id,
            ],
            [
                'seed_key' => 'north-coast-sunset-cruise',
                'name' => 'North Coast Sunset Cruise',
                'description' => 'Evening cruise along the Mediterranean shoreline with sunset views, blending calm waters, relaxed pacing, and a scenic end-of-day atmosphere along the coast.',
                'image' => 'https://images.unsplash.com/photo-1500375592092-40eb2168fd21?auto=format&fit=crop&w=1400&q=80',
                'type' => 'activity',
                'location' => 'North Coast, Marsa Matrouh',
                'city' => 'Marsa Matrouh',
                'civilization_id' => $modern->id,
                'region_id' => $matrouh->id,
            ],
        ];

        foreach ($items as $item) {
            $query = Attraction::query();

            if ($item['type'] === 'activity') {
                $query->updateOrCreate(['seed_key' => $item['seed_key']], $item);

                continue;
            }

            $query->firstOrCreate(['seed_key' => $item['seed_key']], $item);
        }
    }
}